# Generated by Django 4.2.30 on 2026-09-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('face_encoding', models.JSONField(blank=True, help_text='128-dimensional face embedding vector or pixel signature', null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'On Time (Present)'), ('LATE', 'Late Arrival'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('punch_latitude', models.FloatField()),
                ('punch_longitude', models.FloatField()),
                ('distance_meters', models.FloatField()),
                ('verification_photo', models.ImageField(blank=True, null=True, upload_to='attendance/punches/%Y/%m/%d/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.employee')),
            ],
            options={
                'ordering': ['-date', '-check_in'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
