# Generated by Django 4.2.30 on 2026-10-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration_hours',
            field=models.FloatField(blank=True, help_text='Hours requested for PERMISSION type', null=True),
        ),
    ]
